plugins {
    id 'com.android.library'
    id 'pushwoosh.android-library'
    id 'pushwoosh.android-minified'
    id 'pushwoosh.lint'
    id 'pushwoosh.dokka'
}

ext{
    targetArtefactIdDev = "pushwoosh-calls-dev"
    targetArtefactId = "pushwoosh-calls"
    targetName = "Pushwoosh Calls"
    targetDescription = "Pushwoosh Calls"
}

apply plugin: 'org.jetbrains.kotlin.android'
apply from: '../scripts/buildSdk/publish.gradle'
apply from: '../scripts/prepareAar/build.gradle'

android {
    namespace "com.pushwoosh.calls"
    testNamespace "com.pushwoosh.calls.test"

    defaultConfig {
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlin {
        jvmToolchain(17)
    }
    kotlinOptions {
        jvmTarget = '11'
        freeCompilerArgs = ["-Xstring-concat=inline"]
    }
}

dependencies {
    api project(':pushwoosh')

    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    testImplementation "org.mockito:mockito-core:${mockito}"
    testImplementation 'org.robolectric:robolectric:4.14.1'
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}

// Custom Javadoc generation for Maven publication
apply from: '../scripts/buildSdk/javadoc.gradle'
