name: "🐞 Bug Report"
description: "Report us a bug"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to create this issue.
        
        The more detailed information filled below will help us to investigate the root cause of the issue faster and fix it.
        This form is for Android native SDK only. If this is a bug for another platform or framework — please create the issue in the corresponded [repository](https://github.com/orgs/Pushwoosh/repositories). We appreciate your cooperation!

  - type: checkboxes
    id: rtfm
    attributes:
      label: Documentation
      description: "Have you checked the relevant integration guide: [Integrate Pushwoosh Android SDK](https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/android-push-notifications/firebase-integration/integrate-pushwoosh-android-sdk) which describes implementation process of the Pushwoosh SDK to your native Android app and follow all the necessary steps?"
      options:
        - label: I've checked the guide, but it doesn't help me to resolve the issue.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short description of the issue. You can add screenshots and screencast to illustrate it.
      placeholder: "Example: When receiving a push with Rich Media in a closed app, Rich Media is not shown."
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Bug severity
      description: |
        How do you rate the severity of this bug?
        For an objective assessment, please take into account how often this bug occurs in everyday app interaction, how serious the consequences of its occurrence (crash, warning, etc.), number of affected users, enviroment where it occurs (stage, production. etc.).
      options:
        - Low
        - Normal
        - High
        - Urgent
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: Describe all the steps needed to reproduce the issue. If an issue is only reproducible under particular circumstances, put all required details here. E.g., if a push is not shown only for a specific API request, provide the full request body. Or, if an issue is reproducible with a particular Rich Media, deep link, etc. — specify it.
      placeholder: | 
        1. Open the app;
        2. Switch it to the background;
        3. Received notification with "root_params" causes the app to crash.
        This happens only if dependency XYZ v.1.2.3 is installed
    validations:
      required: true
  - type: dropdown
    id: affected-version
    attributes:
      label: Your Pushwoosh Android SDK version
      description: Your Android SDK version which was integrated to the app. You may find it on the [releases page](https://github.com/Pushwoosh/pushwoosh-android-sdk/releases)
      options:
        - 6.7.15
        - 6.7.14
        - 6.7.13
        - 6.7.14
        - 6.7.12
        - 6.7.11
        - 6.7.10
        - 6.7.8
        - 6.7.7
        - 6.7.6
        - 6.7.5
        - 6.7.4
        - 6.7.3
        - 6.7.2
        - 6.7.1
        - 6.7.0
        - 6.6.17
        - 6.6.16
        - 6.6.15
        - 6.6.14
        - 6.6.13
        - 6.6.12
        - 6.6.11
        - 6.6.10
        - 6.6.9
        - 6.6.8
        - 6.6.7
        - 6.6.6
        - 6.6.5
        - 6.6.4
        - 6.6.3
        - 6.6.2
        - 6.6.1
        - 6.6.0
        - 6.5.4
        - 6.5.3
        - 6.5.2
        - 6.5.1
        - 6.5.0
        - 6.4.4
        - 6.4.3
        - 6.4.2
        - 6.4.1
        - 6.4.0
        - 6.3.7
        - 6.3.6
        - 6.3.5
        - 6.3.4
        - 6.3.3
        - 6.3.2
        - 6.3.1
        - 6.3.0
        - 6.2.11
        - 6.2.10
        - 6.2.9
        - 6.2.8
        - 6.2.7
        - 6.2.6
        - 6.2.5
        - 6.2.4
        - 6.2.3
        - 6.2.2
        - 6.2.1
        - 6.2.0
        - 6.1.5
        - 6.1.4
        - 6.1.3
        - 6.1.2
        - 6.1.1
        - 6.1.0
        - 6.0.7
        - 6.0.6
        - 6.0.5
        - 6.0.4
        - 6.0.3
        - 6.0.2
        - 6.0.1
        - 6.0.0
        - Other — specify it in the description
    validations:
      required: true
  - type: input
    id: last-worked
    attributes:
      label: Last worked Pushwoosh Android SDK version (if any)
      description: Is there a version that worked well? If so, please specify.
  - type: textarea
    id: platform-versions
    attributes:
      label: Affected Android versions/devices
      description: Please specify the Android platform, device model and custom distributions (if any) on which this issue occurs. If the issue occurs when building, then specify the target platform.
      placeholder: | 
        E.g. Android 13 on a Google Pixel 3a XL,
        MIUI 14.0.8.0 on Xiaomi 13 Ultra,
        One UI Core 5.1 on a Samsung Galaxy M13 5G, etc.
    validations:
      required: true
  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Have you found a workaround for this issue? Please tell us — this may help other people to continue their work while waiting for this issue to be resolved.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: After reproducing the issue, copy device console logs and paste them here "as is". This code block will be formatted automatically, so no additional formatting is needed. If the issue occurs when building, then provide us building logs here.
      render: shell
